name: Docker Image Build Pipeline

on:
  push:
    branches: ['**']

jobs:
  build:
    name: Build i2b2-webclient image
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Check if secrets exist and output a boolean flag
      - name: Check for Docker Secrets
        id: secret-check
        run: |
          if [ -n "${{ secrets.DOCKER_LOGIN_TOKEN }}" ]; then
            echo "has_secrets=true" >> $GITHUB_OUTPUT
          else
            echo "has_secrets=false" >> $GITHUB_OUTPUT
          fi

      # Only attempt login if secrets are present
      - name: Login to Docker Registry
        if: steps.secret-check.outputs.has_secrets == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HOST }}
          password: ${{ secrets.DOCKER_LOGIN_TOKEN }}

      - name: Determine tag
        id: vars
        run: |
          echo "web_tag=${{ github.ref_name }}" >> $GITHUB_ENV
          echo "Using tag: $web_tag"

      - name: Build and Push image
        env:
          has_secrets: ${{steps.secret-check.outputs.has_secrets}}
        run: |
          # Fails the script immediately if a command exits with a non-zero status
          set -e 
          # Provide local fallbacks if secrets are missing during a fork/clone run
          export docker_username=${{ secrets.DOCKER_HOST || 'localuser' }}
          export docker_reponame=${{ secrets.DOCKER_REPO || 'i2b2' }}
                    
          cd docker/
          bash create_docker_image.sh "$WEBCLIENT_TAG"